회원 테이블 생성
CREATE TABLE MEMBER (
ID VARCHAR2(50) NOT NULL PRIMARY KEY,
PW VARCHAR2(50) NOT NULL,
CLASSIFY VARCHAR2(50) NOT NULL,
NAME VARCHAR2(50) NOT NULL,
TEL VARCHAR2(50) NOT NULL,
NICKNAME VARCHAR2(50) NOT NULL
)

기업정보 테이블 생성
CREATE TABLE COMPANY (
ID VARCHAR2(50) NOT NULL PRIMARY KEY,
NAME VARCHAR2(50) NOT NULL,
COMPANY VARCHAR2(50) NOT NULL,
COM_INFO VARCHAR2(3000) NOT NULL,
COM_IMG VARCHAR2(50) NOT NULL,
PRODUCT VARCHAR2(50) NOT NULL,
EXPERIENCE VARCHAR2(50) NOT NULL,
EX_INFO VARCHAR2(3000) NOT NULL,
PEOPLE NUMBER(30) NOT NULL,
LOCATION VARCHAR2(50) NOT NULL
)

예약현황 테이블 생성
CREATE TABLE RESERVATION (
RES_NUM NUMBER(30) NOT NULL PRIMARY KEY,
NICKNAME VARCHAR2(50) NOT NULL,
CONSTRAINT FK_RESERVATION FOREIGN KEY (NICKNAME) REFERENCES MEMBER (NICKNAME),
DATE VARCHAR2(50) NOT NULL,
EXPERIENCE VARCHAR2(50) NOT NULL,
PEOPLE NUMBER(30) NOT NULL
)

리뷰 테이블 생성
CREATE TABLE REVIEW(
REV_NUM NUMBER(30) NOT NULL PRIMARY KEY,
COMPANY VARCHAR2(50) NOT NULL,
TITLE VARCHAR2(50) NOT NULL,
NICKNAME VARCHAR2(50) NOT NULL,
CONSTRAINT FK_ FOREIGN KEY (NICKNAME) REFERENCES MEMBER (NICKNAME),
CONTENT VARCHAR2(3000) NOT NULL
)

시퀀스 생성(예약현황)
CREATE SEQUENCE RES_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999
CYCLE

시퀀스 생성(리뷰)
CREATE SEQUENCE REV_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 9999
CYCLE

모든 테이블 확인
SELECT * FROM USER_OBJECTS WHERE OBJECT_TYPE='TABLE'

테이블 제거
drop table diary

테이블 확인
select * from MEMBER
select * from CONSULTANT
select * from REVIEW
select * from C_PROFILE
select * from RESERVATION
select * from DIARY

테이블 값 삽입
INSERT INTO C_PROFILE values('consultant@naver.com','상담사','매주 수요일 6시','서울대 심리학과 졸업','상담 잘해요',20)

테이블 값 제거
delete from reservation where pro_email='consultant@naver.com'

row_num(), over()을 이용한 순번 매기기
SELECT * FROM (
           SELECT a.*,ROW_NUMBER() OVER(ORDER BY rev_num DESC) AS rnum FROM review a
        ) WHERE rnum >=1 and rnum<=9;